### PR TITLE
Collin/error handling

### LINKED ISSUE #262: Unsafe error handling in Orchestrator
[Original Issue](https://github.com/althea-net/cosmos-gravity-bridge/issues/351)

 _Surfaced from @informalsystems audit of [Althea Gravity Bridge](https://github.com/althea-net/cosmos-gravity-bridge) at commit [19a4cfe](https://github.com/althea-net/cosmos-gravity-bridge/commit/19a4cfe3b9ee41285ae99adb220d111363e56aa1)_
 
 **severity**: High 
 **type**: Implementation bug
 **difficulty**: Intermediate
 
 # Involved artifacts
 
- [Orchestrator](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator)
 
 
 # Description
 
 The codebase has generous use (hundreds) of `panic`-causing statements: `unwrap()`, `panic!()`, `assert`, `assert_eq`, `assert_ne` and `expect`. In some cases they are safe, but we have identified many cases for which it is unclear whether the asserted condition is always true, or can be violated due to e.g. network errors or misbehavior/bugs in other Gravity Bridge components.
 
 Below we provide some examples of those statements, characterized into three categories:
 ### Assertions that depend on other Gravity Bridge components
 
 These assertions may be fine _as soon as the other Gravity components behave correctly_. Checking whether this is indeed true is an extremely complex and time-consuming process. Also, even if those components do behave correctly, there is always a possibility of some bug, or a malicious action.
 
[`orchestrator/gravity_utils/src/types/valsets.rs#L151`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/gravity_utils/src/types/valsets.rs#L151-152)

```rust
       for member in self.members.iter() {
           if let Some(eth_address) = member.eth_address {
               if let Some(sig) = signatures_hashmap.get(&eth_address) {
                   assert_eq!(sig.get_eth_address(), eth_address);
                   assert!(sig.get_signature().is_valid());
```
       
       
           
             
      
This is probably safe as the `valset` updates are coming from trusted `validators`. Now the question is:
       
* what if due to some bug an invalid signature is included?
* what if a malicious validator intentionally includes a wrong signature? This will lead to all other Orchestrators stopping, and all other validators being slashed.
 
- [`orchestrator/gravity_utils/src/types/valsets.rs#L167`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/gravity_utils/src/types/valsets.rs#L167)

```rust
       // the go code verifies signatures, if we ever see this it means
       // that something has gone horribly wrong with our parsing or ordering
       // in the orchestrator, therefore we panic.
       panic!(
           "Found invalid signature for {} how did this get here?",
           sig.get_eth_address()
       )
```
       
   
Same as above.
 
- [`orchestrator/relayer/src/find_latest_valset.rs#L93`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/relayer/src/find_latest_valset.rs#L93)

```rust
       if cosmos_valset != *ethereum_valset {
           // if this is not true then we have a logic error on the Cosmos chain
           // or with our Ethereum search
           assert_eq!(cosmos_valset.nonce, ethereum_valset.nonce);
```
         
If, as the comment says, there is indeed some logic error, is this the valid reason for all Orchestrators stopping and validators being slashed?
 
* [`orchestrator/relayer/src/valset_relaying.rs#L49-53`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/relayer/src/valset_relaying.rs#L49-53)

```rust
       let valset = get_valset(grpc_client, latest_nonce).await;
       if let Ok(Some(valset)) = valset {
           assert_eq!(valset.nonce, latest_nonce);
```
       
         
This is probably safe, because the `rpc` calls ask for the specific nonce; but what if there is a bug in the RPC call?
 
- [`orchestrator/ethereum_gravity/src/utils.rs#L144`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/ethereum_gravity/src/utils.rs#L144)
 
- [`orchestrator/ethereum_gravity/src/utils.rs#L168`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/ethereum_gravity/src/utils.rs#L168)
 
- [`orchestrator/ethereum_gravity/src/utils.rs#L119`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/ethereum_gravity/src/utils.rs#L119)
 
- [`orchestrator/ethereum_gravity/src/utils.rs#L94`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/ethereum_gravity/src/utils.rs#L94)

       
```rust
       // the go represents all nonces as u64, there's no
       // reason they should ever overflow without a user
       // submitting millions or tens of millions of dollars
       // worth of transactions. But we properly check and
       // handle that case here.
       let real_num = Uint256::from_bytes_be(&val);
       Ok(downcast_uint256(real_num).expect("Valset nonce overflow! Bridge Halt!"))
```
       
         
This depends on the correct behavior of the Solidity contract, and on the nonces never overflowing 64 bits. While unlikely, both conditions still could be violated.
 
 
 ### Assertions in the initialization phases or in the client code
 
ignores `CosmosGRPCError` which can happen because of reasons not related to balance or requesting batch.
       
- [`orchestrator/gbt/src/client/cosmos_to_eth.rs#L59`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/gbt/src/client/cosmos_to_eth.rs#L59)
- [`orchestrator/gbt/src/client/cosmos_to_eth.rs#L109`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/gbt/src/client/cosmos_to_eth.rs#L109)
 
- ignores `Web3Error` which can happen without incorrect gravity address or ERC20 queries.
       
- [`orchestrator/gbt/src/client/eth_to_cosmos.rs#L25`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/gbt/src/client/eth_to_cosmos.rs#L25)
- [`orchestrator/gbt/src/client/eth_to_cosmos.rs#L32`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/gbt/src/client/eth_to_cosmos.rs#L32)
* [`orchestrator/gbt/src/client/eth_to_cosmos.rs#L39`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/gbt/src/client/eth_to_cosmos.rs#L39)
 
* There are other `expect`s in the code. But we do not mention them as they are at the initialization phase or due to user specific errors.
       
* Failed to create directory or write to file.
* Failed to load cosmos or eth keys.
 
 
 These errors probably won't lead to severe consequences, such as validator slashing. But they will definitely occur many times, and the error will be communicated to the user via `panic`ing and printing a stack trace. This is not the best way to communicate errors to the user, and should be improved.
 ### Vacuously true assertions
 
 These assertions are guaranteed to be safe due to the code structure, and can thus be removed. Keeping them in the code makes code inspection exceptionally difficult, as we spend time on false positives. Minimizing the usage of them would be helpful for future code inspections. Here are a couple of examples:
 
* [`orchestrator/gravity_utils/src/types/batches.rs#L59-L60`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/gravity_utils/src/types/batches.rs#L59-L60)
       
* safe because of the `Vec`s are populated in a same length loop.
 
* [`orchestrator/ethereum_gravity/src/valset_update.rs#L26`](https://github.com/althea-net/cosmos-gravity-bridge/tree/19a4cfe3b9ee41285ae99adb220d111363e56aa1/orchestrator/ethereum_gravity/src/valset_update.rs#L26)
       
* safe as the check is done before reaching this call.
 
 
 # Problem Scenarios
 
 As there is a very large number (hundreds) of `panic`-resulting statements, it is close to impossible to enumerate all possible problem scenarios. Here are a few example ones:
 
* Due to a bug in other Gravity Bridge component, an input comes to the Orchestrator that triggers one of the `panic`-statements;
 
* The input triggering a panic is maliciously crafted (this may happen even from a validator side);
 
* A network error occurs, which propagates to one of the panic statements.
 
 
 The effect depends on in the part of the Orchestrator in which the panic occurs. A panic in the initialization code will probably result only in the user inconvenience and annoyance. If the panic occurs a long time after the Orchestrator has been started, it will stop, and this may lead to validators being slashed without malicious actions from their part.
 
 **It should be noted that Orchestrator is a single binary responsible for all kinds of operations: a panic triggered during any of those (even seemingly unimportant) will cause the whole processing to stop, with the aforementioned severe consequences.**
 # Recommendation
 ### Short term
 
 We recommend different course of action depending of the panic category:
 
* **Assertions that depend on other Gravity Bridge components**:
       
* Carefully inspect the code in the other components on which the assertion depends;
* Move error-handling code in the Orchestrator to the input-receiving boundary;
* For the cases when this is not possible, propagate the errors using `Result`s to the top level;
* At the top level, implement a uniform error handling with alerts issued to validators;
* _Do not stop processing of other legitimate, non-erroneous requests_.
 
* **Assertions in the initialization phases or in the client code**:
       
* Move error-handling code to the input-receiving boundary or propagate errors to the top level;
* At the top level, implement a uniform error handling with meaningful error messages issued to the user.
 
* **Vacuously true assertions**:
       
* Inspect the code, and if the assertion proves to be vacuously true, remove it.
 
 
 ### Long term
 
 Refactor the Orchestrator into independent binaries each responsible for different operation kind. Ensure that all binaries responsible for possible validator slashing adhere to the highest possible security standards; they should not stop under any circumstances, and should employ defensive programming techniques against possible failures in other components.

### PR DESCRIPTION
**Pull request by cbrit**
Closes #262 

Addresses problematic ~~and non-idiomatic~~ error handling. 

I judged a few assertions to be unnecessary because they asserted statements that were definitively made true by nearby code.

-  Two assertions in `gravity_utils/src/types/batches.rs` were removed because the loop immediately before them constructs them.
- An assertion in `ethereum_gravity/src/valset_update.rs` was removed because the comparison was tested earlier in valset_relaying.rs via `latest_cosmos_valset.nonce > current_eth_valset.nonce` making this check redundant.

~~I also refactored a number of unusual `Result` checks as `match` blocks.~~

EDIT: Crossed out items were not included in branch remake after Eric's PR replace web30 and other libraries.

### CODE REVIEW

**Comment by cbrit** [comment]
I think this is ready for feedback. Apologies for some file including formatting fixes that I should have saved for another PR.

**Comment by cbrit** [comment]
These were two particular lines called out by the issue that I want to get your thoughts on. The assertions seems trivial but depend on external services behaving properly. If they don't, it will panic obviously. What's the best way to approach this?

https://github.com/PeggyJV/gravity-bridge/blob/e92bfda01d4606cce4f52c14a135f9d2269005bd/orchestrator/gravity_utils/src/types/valsets.rs#L151-L152

**Comment by EricBolten** [comment]
Hey @cbrit, unfortunately another casualty of large changes to main in order to be mergeable.

File: orchestrator/relayer/src/valset_relaying.rs [hunk 1]
```diff
@@ -56,49 +56,66 @@ pub async fn relay_valsets(
...
+                            assert_eq!(cosmos_valset.nonce, confirm.nonce);
+                        }
+
+                        let hash =
+                            encode_valset_confirm_hashed(gravity_id.clone(), cosmos_valset.clone());
+
+                        // there are two possible encoding problems that could cause the very rare sig failure bug,
+                        // one of them is that the hash is incorrect, that's not probable considering that
+                        // both Geth and Clarity agree on it. but this lets us check
+                        info!("New valset hash {}", bytes_to_hex_str(&hash),);
```
Comment (EricBolten) [inline orchestrator/relayer/src/valset_relaying.rs:80]: Probably don't want that trailing comma.

File: orchestrator/relayer/src/find_latest_valset.rs [hunk 2]
```diff
@@ -81,19 +81,30 @@ pub async fn find_latest_valset(
...
+        // if this is true then we have a logic error on the Cosmos chain
         // or with our Ethereum search
-        assert_eq!(cosmos_valset.nonce, ethereum_valset.nonce);
+        if cosmos_valset.nonce != ethereum_valset.nonce {
+            error!(
+                "Cosmos valset nonce ({}) and Ethereum valset nonce ({}) are not the same!",
+                cosmos_valset.nonce, ethereum_valset.nonce
+            );
+            return Err(GravityError::DifferingValsetNoncesError(
+                ValsetsNoncePair::from((cosmos_valset.nonce, ethereum_valset.nonce)),
```
Comment (EricBolten) [inline orchestrator/relayer/src/find_latest_valset.rs:105]: There's no need to use the indirection of calling `::from` here (and defining it for the struct), you could simply instantiate it directly.

**Review by EricBolten — COMMENTED** [review]
Left a few comments. I think it would also be wise as a sanity check to run orchestrator changes through the e2e tests by hand until we get it integrated into CI (if you haven't already done that).

File: orchestrator/gravity_utils/src/error.rs [hunk 3]
```diff
@@ -24,6 +23,8 @@ use std::string::FromUtf8Error;
 use tokio::time::error::Elapsed;
 use tonic::Status;
 
+use crate::types::ValsetsNoncePair;
```
[the remark this answers is not in the document]
Comment (cbrit) [reply orchestrator/gravity_utils/src/error.rs:26]: For some reason vscode's suggested fix puts them at the bottom with a gap like that.

File: orchestrator/relayer/src/find_latest_valset.rs [hunk 4]
```diff
@@ -81,19 +81,26 @@ pub async fn find_latest_valset(
...
-        return;
+        return Ok(());
     }
     let cosmos_valset = cosmos_valset.unwrap();
     if cosmos_valset != *ethereum_valset {
-        // if this is not true then we have a logic error on the Cosmos chain
+        // if this is true then we have a logic error on the Cosmos chain
         // or with our Ethereum search
-        assert_eq!(cosmos_valset.nonce, ethereum_valset.nonce);
+        if cosmos_valset.nonce != ethereum_valset.nonce {
```
Comment (EricBolten) [inline orchestrator/relayer/src/find_latest_valset.rs:99]: After thinking more about it...is this error recoverable? The caller is retrieving the latest Ethereum valset, taking the nonce, and then asking the Cosmos chain for the valset it has for that nonce. As it says in the comment, for these to be different, we'd either be searching incorrectly for the latest Ethereum valset, or the Cosmos chain responds to the query for a valset with a specific nonce by returning a valset with an entirely different nonce. That sounds like programmer error rather than something that can recover in production.

**Comment by EricBolten** [comment]
Responding to your comment about the signature assertions in `valsets.rs`, the address check is probably useless, the hashmap is created using the address from the signature object. As to the second one, it's no longer present, as if the signature is invalid it's going to fail to `recover` anyway, and it doesn't seem to be worth crashing if someone submits an invalid signature.

File: orchestrator/relayer/src/find_latest_valset.rs [hunk 5]
```diff
@@ -81,20 +81,19 @@ pub async fn find_latest_valset(
...
     } else if cosmos_valset.is_none() {
         error!("Cosmos does not have a valset for nonce {} but that is the one on the Ethereum chain! Possible bridge highjacking!", ethereum_valset.nonce);
-        return;
+        return Ok(());
     }
     let cosmos_valset = cosmos_valset.unwrap();
     if cosmos_valset != *ethereum_valset {
-        // if this is not true then we have a logic error on the Cosmos chain
-        // or with our Ethereum search
-        assert_eq!(cosmos_valset.nonce, ethereum_valset.nonce);
```
Comment (EricBolten) [inline orchestrator/relayer/src/find_latest_valset.rs:96]: If this condition really is programmer error we may want to leave this assertion in.

**Review by zmanian — APPROVED** [review]
